name: Publish Preview Release

on:
  push:
    branches:
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_on_merge:
    name: Tag and Publish UPM package
    uses: realitycollective/reusableworkflows-reality-toolkit/.github/workflows/upversionandtagrelease.yml@1.0.1
    with:
      runs-on: Windows, unity
      build-type: pre-release
    secrets: inherit